spring.application.name=replicador-documental
server.port=8082
spring.datasource.url=jdbc:oracle:thin:@//192.168.21.147:1521/TEST
spring.datasource.username=desierra
spring.datasource.password=Test2030
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# SOAP Client Configuration
soap.client.default-uri=http://192.168.21.15:7801/carpeta
soap.client.uri.solicitar-archivo=/solicitar_archivo
soap.client.action.solicitar-archivo=http://tempuri.org/solicitar_archivo_ms/ReqSolicitarArchivo

# Document Registration Service
document.registration.api.url=https://ms-tr-gestor-documental-194964492367.us-east1.run.app/api/register

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true

logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.received=DEBUG



